# Generated by Django 4.1.4 on 2022-12-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="birthdate",
            field=models.DateField(default=None, null=True),
        ),
    ]
