# Generated by Django 4.1.4 on 2022-12-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movieorder_movie_movieorder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movieorder",
            old_name="buyed_ad",
            new_name="buyed_at",
        ),
    ]
